"""Agent-testing utilities for SolidWorks MCP custom agents."""

from .harness import pretty_json, run_validated_prompt
from .history_db import (
    DEFAULT_DB_PATH,
    ErrorRecord,
    find_conversation_events,
    find_recent_errors,
    find_run_timeline,
    get_design_session,
    init_db,
    insert_conversation_event,
    insert_evidence_link,
    insert_model_state_snapshot,
    insert_plan_checkpoint,
    insert_sketch_graph_snapshot,
    insert_tool_call_record,
    list_evidence_links,
    list_model_state_snapshots,
    list_plan_checkpoints,
    list_sketch_graph_snapshots,
    list_tool_call_records,
    update_plan_checkpoint,
    upsert_design_session,
)
from .retrieval_index import build_local_retrieval_index
from .schemas import (
    DocsPlan,
    ManufacturabilityReview,
    RecoverableFailure,
    ToolRoutingDecision,
)

__all__ = [
    "DEFAULT_DB_PATH",
    "DocsPlan",
    "ErrorRecord",
    "ManufacturabilityReview",
    "RecoverableFailure",
    "ToolRoutingDecision",
    "build_local_retrieval_index",
    "find_conversation_events",
    "get_design_session",
    "find_recent_errors",
    "find_run_timeline",
    "init_db",
    "insert_evidence_link",
    "insert_model_state_snapshot",
    "insert_plan_checkpoint",
    "insert_sketch_graph_snapshot",
    "insert_tool_call_record",
    "insert_conversation_event",
    "list_evidence_links",
    "list_model_state_snapshots",
    "list_plan_checkpoints",
    "list_sketch_graph_snapshots",
    "list_tool_call_records",
    "pretty_json",
    "run_validated_prompt",
    "update_plan_checkpoint",
    "upsert_design_session",
]
